#####################################################################################
# MySQL Configuration
#####################################################################################
mysql:
  use-mysql: false
  host: localhost
  port: 3306
  database: bountiesplus
  username: root
  password: ""
  data-migrated: false
#####################################################################################
# Custom Placeholders - Customize the way placeholders resolve
#####################################################################################
custom-placeholders:
  bounty-target-fallback: "None"
  bounty-status-no-expiration: "No expiration"
#####################################################################################
# Debug / General Bounty Settings
#####################################################################################
debug-enabled: false
restrict-same-ip-bounties: false
time:
  allow-time: true
  require-time: false
  default-bounty-duration: 1440
  min-bounty-time: 3600
  max-bounty-time: 86400
enable-shop: true
allow-expired-skulls: true
allow-offline-players: true
require-skull-turn-in: true
min-bounty-amount: 100
max-bounty-amount: 1000000
#####################################################################################
# Anonymous Bounties Settings
#####################################################################################
anonymous-bounties:
  enabled: true
  base-percentage: 15.0
  minimum-cost: 50.0
  maximum-cost: 5000.0
#####################################################################################
# Tax Settings
#####################################################################################
bounty-place-tax-rate: 10.0
bounty-cancel-tax-rate: 10.0
tax-total-value: false
#####################################################################################
# Tablist Settings
#####################################################################################
tablist-modification:
  enabled: true
  format: "&c[Bounty] %bountiesplus_player_name%"
###################################################################################
# Blacklist Items from being added to a bounty (Supports NBT tags for Custom Items
###################################################################################
blacklisted-items:
  - "DIAMOND_SWORD"
  - "NETHERITE_AXE"
blacklisted-nbt-items:
  - nbt_key: "item_type"
    nbt_value: "tracker"
  - nbt_key: "item_type"
    nbt_value: "uav"
###################################################################################
# Customize Skull that drops when a player with bounty is killed
###################################################################################
bounty-skull:
  name: "&c&l☠ &4Bounty Head of %target% &c&l☠"
  lore:
    - "&7This is the head of a wanted criminal!"
    - "&7Player: &e%target%"
    - "&7Total Bounty: &a$%total_bounty%"
    - "&7Bounties: &f%bounty_count%"
    - "&7Killed by: &c%killer%"
    - "&7Time of Death: &6%death_time%"
    - ""
    - "&eRight-click to turn in for rewards!"
    - "&cWarning: Head will expire in 24 hours"
  enchantment-glow: true
###################################################################################
# Boosted Bounties Settings
###################################################################################
boosted-bounties:
  enabled: true
  boost-interval: 120
  multiplier-chances:
    "2.0": 50.0
    "3.0": 30.0
    "5.0": 20.0
  boosted-title: "&aBounty Boosted!"
  boosted-subtitle: "&e%target% &aby &e%multiplier%x"
  enable-title-subtitle: true
  bossbar:
    enabled: true
    display-before-boost: 3
    message: "&6Next Boosted Bounty in %time%"
###################################################################################
# Frenzy Mode Settings
###################################################################################
frenzy:
  enabled: true
  frenzy-interval: 180  # Time between frenzy events in minutes
  multiplier-chances:
    "2.0": 50.0  # 50% chance for 2x multiplier
    "3.0": 30.0  # 30% chance for 3x multiplier
    "5.0": 20.0  # 20% chance for 5x multiplier
  bossbar:
    enabled: true
    display-before-frenzy: 5  # Seconds to display boss bar before frenzy starts
    message: "&cFrenzy Mode Starting in %time%"  # Boss bar message with time placeholder
###################################################################################
# Sound Settings
###################################################################################
bounty-sound:
  enabled: true
  sound: "ENTITY_BLAZE_SHOOT"
  volume: 1.0
  pitch: 1.0